// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { useUser, SignInButton, SignOutButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import Image from "next/image";
import { type RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  // console.log(`user obj -> ${JSON.stringify(user, null, 5)}`);

  if (!user) return null;

  return (
    <div className="flex gap-3 w-full">
      <Image
        width={50} height={50}
        src={user.profileImageUrl}
        alt="Profile Image"
        className="rounded-full"
      />
      <input
        type="text" placeholder="What's on your mind?"
        className="bg-transparent grow outline-none"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div className="p-4 border-b border-slate-400 flex gap-3" key={post.id}>
      <Image
        width={50} height={50}
        src={author.profileImageUrl}
        alt={`@${author.username}'s profile picture`}
        className="rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex text-slate-300 gap-2">
          <span>{`@${author.username}`}</span> <span className="font-thin">{` · ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
}

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return (<div>Loading...</div>);

  if (!data) return (<div>There was an error loading posts...</div>);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen"> {/* #15162c */}
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center"><SignInButton /></div>
            )}
            {/* <SignOutButton /> */}
            {!!user.isSignedIn && (
              <CreatePostWizard />
            )}
          </div>
          <div className="flex flex-col">
            {
              [...data, ...data]?.map((fullPost) => (
                <PostView {...fullPost} key={fullPost.post.id}/>
              ))
            }
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
